export const FEATURE_KEYS = [
  "ai_conversation",
  "practice_sets",
  "dictionary_reader",
  "audio_courses",
  "listening_lab",
  "coaching_material",
  "one_on_one_coaching",
  "inner_circle_group_coaching",
  "group_coaching_schedule",
  "flashcards",
  "course_library",
  "video_threads",
  "certificates",
  "ai_chat",
  "mandarin_accelerator",
  "audio_accelerator_edition",
  "tone_mastery",
  "listening_training",
  "notepad",
  "assignment_feedback",
  "lab_assistant",
  "assignment_review_text",
  "assignment_review_vocal",
  "assignment_review_diary",
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[number];

const FEATURE_META = {
  ai_conversation: { label: "AI Conversation Bot", description: "Voice practice with an AI tutor" },
  practice_sets: { label: "Practice Sets", description: "Interactive exercises and quizzes" },
  dictionary_reader: { label: "Dictionary & Reader", description: "Built-in Chinese dictionary and text reader" },
  audio_courses: { label: "Audio Courses", description: "Audio-first course lessons and exercises" },
  listening_lab: { label: "YouTube Listening Lab", description: "YouTube-based listening practice" },
  coaching_material: { label: "Legacy Coaching Material", description: "Legacy umbrella permission retained for compatibility" },
  one_on_one_coaching: { label: "1:1 Coaching", description: "Private coaching materials" },
  inner_circle_group_coaching: { label: "Inner Circle Group Coaching", description: "Inner Circle group coaching materials" },
  group_coaching_schedule: { label: "Group Coaching Schedule", description: "Group coaching calendar and schedule" },
  flashcards: { label: "Flashcards", description: "Spaced-repetition vocabulary review" },
  course_library: { label: "Course Library", description: "Published course library content" },
  video_threads: { label: "Video Threads", description: "Interactive video response activities" },
  certificates: { label: "Certificates", description: "Course completion certificates" },
  ai_chat: { label: "AI Chat", description: "Text-based AI conversation assistant" },
  mandarin_accelerator: { label: "Mandarin Accelerator", description: "Mandarin Accelerator learning path" },
  audio_accelerator_edition: { label: "Audio Accelerator Edition", description: "Accelerator audio edition content" },
  tone_mastery: { label: "Tone Mastery", description: "Tone practice and mastery tools" },
  listening_training: { label: "Listening Training", description: "Accelerator listening training" },
  notepad: { label: "Notepad", description: "Personal learning notes" },
  assignment_feedback: { label: "Assignment Feedback", description: "Personalized reviewer feedback on assignments" },
  lab_assistant: { label: "Lab Assistant (Legacy)", description: "Legacy compatibility key for the baseline support widget" },
  assignment_review_text: { label: "Assignment Review (Text)", description: "Review text assignment submissions" },
  assignment_review_vocal: { label: "Assignment Review (Vocal)", description: "Review vocal assignment submissions" },
  assignment_review_diary: { label: "Assignment Review (Diary)", description: "Review diary assignment submissions" },
} satisfies Record<FeatureKey, { label: string; description: string }>;

export const FEATURE_DEFINITIONS = FEATURE_KEYS.map((key) => ({
  key,
  ...FEATURE_META[key],
}));
