import { pgTable, text, timestamp, doublePrecision } from "drizzle-orm/pg-core";

export const activeStudents = pgTable("active_students", {
  contactId: text("contact_id").primaryKey(),
  firstName: text("first_name"),
  lastName: text("last_name"),
  email: text("email"),
  phone: text("phone"),
  tags: text("tags"),
  lastActivity: text("last_activity"),
  lastNote: text("last_note"),
  salesRep: text("sales_rep"),
  country: text("country"),
  timezone: text("timezone"),
  city: doublePrecision("city"), // Note: Schema reports this as double precision
  state: doublePrecision("state"), // Note: Schema reports this as double precision
  website: doublePrecision("website"), // Note: Schema reports this as double precision
  dateOfBirth: timestamp("date_of_birth", { withTimezone: true }),
  companyName: doublePrecision("company_name"), // Note: Schema reports this as double precision
  postalCode: text("postal_code"),
  customerSupportSubject: text("customer_support_subject"),
  generalNotes: text("general_notes"),
  currency: text("currency"),
  paidTotal: text("paid_total"),
  paymentStatus: text("payment_status"),
  whyTheyWannaLearnChinese: text("why_they_wanna_learn_chinese_what_s_their_main_goal"),
  referralEmail: text("referral_email"),
  description: text("description"),
  source: text("source"),
  yourMessage: text("your_message"),
  lastPortalLogin: text("last_portal_login"),
  contactType: text("contact_type"),
  ticketSubmitter: text("ticket_submitter"),
  fullAddress: text("full_address"),
  col1on1CoachingFathomLink: text("col_1on1_coaching_fathom_link"),
  col1on1CoachingProgress: text("col_1on1_coaching_progress"),
  col1on1CoachName: text("col_1on1_coach_name"),
  cmbpLevel: text("cmbp_level_which_section_is_student_on"),
  ticketAssignee: text("ticket_assignee"),
  products: text("products"),
  mayWeContactYou: text("may_we_contact_you_for_follow_up_questions_or_testimonials"),
  offers: text("offers"),
  whatDidYouLikeMost: text("what_did_you_like_most_about_our_service"),
  wouldYouRecommend: text("would_you_recommend_our_services_to_others"),
  lastAppointmentConfirmed: text("last_appointment_confirmed_open"),
  whatCanWeDoToImprove: text("what_can_we_do_to_improve_our_services"),
  homeworkType: text("homework_type"),
  additionalPhones: text("additional_phones"),
  additionalNotes: text("additional_notes"),
  loomLink: text("loom_link"),
  assignedTo: text("assigned_to"),
  courseEligibility: text("course_eligibility"),
  col1on1Eligibility: text("col_1_1_eligibility"),
  productLine: text("product_line"),
  addOnPurchased: text("add_on_purchased"),
  coachName: text("coach_name"),
  welcomeLoom: text("welcome_loom"),
  workflowsActive: text("workflows_active"),
  workflowsFinished: text("workflows_finished"),
  upsellRecommend: text("upsell_recommend"),
  accessPlan: text("access_plan"),
  businessName: text("business_name"),
  streetAddress: text("street_address"),
  upsellCoachNote: text("upsell_coach_note"),
  opportunities: text("opportunities"),
  
  // Double precision fields that might be ratings or numeric data
  serviceQuality: doublePrecision("how_would_you_rate_the_overall_quality_of_the_service_provided"),
  dnd: doublePrecision("dnd"),
  additionalEmails: doublePrecision("additional_emails"),
  followers: doublePrecision("followers"),
  lessonNumber: doublePrecision("which_lesson_number_is_the_student_at"),
  additionalComments: doublePrecision("any_additional_comments_or_suggestions"),
  communicationRating: doublePrecision("how_would_you_rate_the_communication_throughout_the_project"),
  updatesOptIn: timestamp("would_you_like_to_receive_updates_and_promotional_offers_from_u", { withTimezone: true }), // Timestamp based on schema
  cleanlinessRating: doublePrecision("how_would_you_rate_the_cleanliness_of_the_work_site_after_compl"),
  professionalismRating: doublePrecision("how_satisfied_are_you_with_the_professionalism_of_our_staff"),
  instructionClarityRating: doublePrecision("how_clear_were_the_instructions_provided_in_the_onboarding_emai"),
  singleLine161f0: doublePrecision("single_line_161f0"),
  loginCounter: doublePrecision("login_counter"),

  // Timestamp fields
  created: timestamp("created", { withTimezone: true }),
  updated: timestamp("updated", { withTimezone: true }),
  productStartDate: timestamp("product_start_date", { withTimezone: true }),
  productEndDate: timestamp("product_end_date", { withTimezone: true }),
  col1on1EndDate: timestamp("col_1_on_1_end_date", { withTimezone: true }),
  cmsTrialStartDate: timestamp("cms_trial_start_date", { withTimezone: true }),
  cmsTrialEndDate: timestamp("cms_trial_end_date", { withTimezone: true }),
  m1FoundationsCompletionDate: timestamp("m1_foundations_completion_date", { withTimezone: true }),
  m2IntermediateCompletionDate: timestamp("m2_intermediate_completion_date", { withTimezone: true }),
  m3AdvancedCompletionDate: timestamp("m3_advanced_completion_date", { withTimezone: true }),
});

export type ActiveStudent = typeof activeStudents.$inferSelect;
export type NewActiveStudent = typeof activeStudents.$inferInsert;
