CREATE INDEX "course_access_user_id_idx" ON "course_access" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "course_access_course_id_idx" ON "course_access" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "lessons_module_id_idx" ON "lessons" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "modules_course_id_idx" ON "modules" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "interaction_attempts_interaction_id_idx" ON "interaction_attempts" USING btree ("interaction_id");--> statement-breakpoint
CREATE INDEX "interaction_attempts_user_id_idx" ON "interaction_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "interactions_lesson_id_idx" ON "interactions" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "lesson_progress_lesson_id_idx" ON "lesson_progress" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "coach_feedback_coach_id_idx" ON "coach_feedback" USING btree ("coach_id");--> statement-breakpoint
CREATE INDEX "submissions_user_id_idx" ON "submissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "submissions_interaction_id_idx" ON "submissions" USING btree ("interaction_id");--> statement-breakpoint
CREATE INDEX "submissions_lesson_id_idx" ON "submissions" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "submissions_reviewed_by_idx" ON "submissions" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "coach_notes_coach_id_idx" ON "coach_notes" USING btree ("coach_id");--> statement-breakpoint
CREATE INDEX "coach_notes_student_id_idx" ON "coach_notes" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "coach_notes_submission_id_idx" ON "coach_notes" USING btree ("submission_id");--> statement-breakpoint
CREATE INDEX "conversation_turns_conversation_id_idx" ON "conversation_turns" USING btree ("conversation_id");--> statement-breakpoint
CREATE INDEX "conversations_user_id_idx" ON "conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "conversations_lesson_id_idx" ON "conversations" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "ai_prompt_versions_prompt_id_idx" ON "ai_prompt_versions" USING btree ("prompt_id");--> statement-breakpoint
CREATE INDEX "ai_prompt_versions_created_by_idx" ON "ai_prompt_versions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "video_uploads_lesson_id_idx" ON "video_uploads" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "kb_chunks_entry_id_idx" ON "kb_chunks" USING btree ("entry_id");--> statement-breakpoint
CREATE INDEX "kb_chunks_file_source_id_idx" ON "kb_chunks" USING btree ("file_source_id");--> statement-breakpoint
CREATE INDEX "kb_entries_category_id_idx" ON "kb_entries" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "kb_file_sources_entry_id_idx" ON "kb_file_sources" USING btree ("entry_id");--> statement-breakpoint
CREATE INDEX "certificates_course_id_idx" ON "certificates" USING btree ("course_id");--> statement-breakpoint
CREATE INDEX "auto_tag_rules_tag_id_idx" ON "auto_tag_rules" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX "auto_tag_rules_created_by_idx" ON "auto_tag_rules" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "student_tags_assigned_by_idx" ON "student_tags" USING btree ("assigned_by");--> statement-breakpoint
CREATE INDEX "tags_created_by_idx" ON "tags" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "bulk_operations_performed_by_idx" ON "bulk_operations" USING btree ("performed_by");--> statement-breakpoint
CREATE INDEX "filter_presets_created_by_idx" ON "filter_presets" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "practice_attempts_practice_set_id_idx" ON "practice_attempts" USING btree ("practice_set_id");--> statement-breakpoint
CREATE INDEX "practice_attempts_user_id_idx" ON "practice_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "practice_exercises_practice_set_id_idx" ON "practice_exercises" USING btree ("practice_set_id");--> statement-breakpoint
CREATE INDEX "practice_set_assignments_practice_set_id_idx" ON "practice_set_assignments" USING btree ("practice_set_id");--> statement-breakpoint
CREATE INDEX "practice_set_assignments_assigned_by_idx" ON "practice_set_assignments" USING btree ("assigned_by");--> statement-breakpoint
CREATE INDEX "practice_sets_created_by_idx" ON "practice_sets" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "chat_conversations_user_id_idx" ON "chat_conversations" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "chat_conversations_lesson_id_idx" ON "chat_conversations" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "chat_messages_conversation_id_idx" ON "chat_messages" USING btree ("conversation_id");