-- Decouple VideoAsk source staging from the temporary Course Library course and
-- native video-thread records created by the first importer. The source form,
-- question, media, and Vocal Hack review rows remain durable and auditable.
ALTER TABLE "videoask_import_projects"
  DROP CONSTRAINT IF EXISTS "videoask_import_projects_course_id_course_library_courses_id_fk";
--> statement-breakpoint
ALTER TABLE "videoask_import_projects"
  DROP CONSTRAINT IF EXISTS "videoask_import_projects_course_id_fkey";
--> statement-breakpoint
ALTER TABLE "videoask_import_projects"
  ALTER COLUMN "course_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "videoask_import_projects"
  ADD CONSTRAINT "videoask_import_projects_course_id_fkey"
  FOREIGN KEY ("course_id") REFERENCES "public"."course_library_courses"("id")
  ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  ADD COLUMN IF NOT EXISTS "sort_order" integer DEFAULT 0 NOT NULL;
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  ADD COLUMN IF NOT EXISTS "source_prompt_text" text;
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  ADD COLUMN IF NOT EXISTS "source_transcript" text;
--> statement-breakpoint
UPDATE "videoask_step_imports" AS source_step
SET
  "sort_order" = native_step."sort_order",
  "source_prompt_text" = native_step."prompt_text",
  "source_transcript" = native_step."transcript_text"
FROM "video_thread_steps" AS native_step
WHERE source_step."step_id" = native_step."id";
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  DROP CONSTRAINT IF EXISTS "videoask_step_imports_step_id_video_thread_steps_id_fk";
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  DROP CONSTRAINT IF EXISTS "videoask_step_imports_step_id_fkey";
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  ALTER COLUMN "step_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "videoask_step_imports"
  ADD CONSTRAINT "videoask_step_imports_step_id_fkey"
  FOREIGN KEY ("step_id") REFERENCES "public"."video_thread_steps"("id")
  ON DELETE set null ON UPDATE no action;
--> statement-breakpoint
-- Remove only the unpublished draft courses generated by the legacy importer.
-- Deleting them sets project.course_id and form_import.lesson_id to NULL while
-- preserving all source-staging and Vocal Hack review rows.
DELETE FROM "course_library_courses"
WHERE "id" IN (
  SELECT "course_id"
  FROM "videoask_import_projects"
  WHERE "course_id" IS NOT NULL
)
AND "title" LIKE 'VideoAsk Migration — %'
AND "status" = 'draft'
AND "is_published" = false;
--> statement-breakpoint
-- Legacy video threads duplicated the source material. Normalized prompt,
-- transcript, order, snapshot, and private media references now live directly
-- on videoask_step_imports, so these generated threads are no longer needed.
DELETE FROM "video_threads"
WHERE "id" IN (
  SELECT DISTINCT "thread_id"
  FROM "videoask_form_imports"
  WHERE "thread_id" IS NOT NULL
    AND "project_id" IN (
      SELECT "id"
      FROM "videoask_import_projects"
      WHERE "course_id" IS NULL
    )
);
